"""
motion_values.json の攻撃名を日本語化する
MHWilds公式の日本語技名に基づく翻訳
"""
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(SCRIPT_DIR, "..", "data", "motion_values.json")

# ====================================================================
# 武器種別翻訳テーブル  英語名 → 日本語名
# ====================================================================

TRANSLATIONS: dict[str, dict[str, str]] = {}

# ─── 大剣 ───
TRANSLATIONS["大剣"] = {
    "Overhead Slash": "縦斬り",
    "Charged Slash Lv1": "溜め斬りLv1",
    "Charged Slash Lv2": "溜め斬りLv2",
    "Charged Slash Lv3": "溜め斬りLv3",
    "Wide Slash": "薙ぎ払い",
    "Rising Slash": "斬り上げ",
    "Offset Rising Slash Lv1": "ずらし斬り上げLv1",
    "Offset Rising Slash Lv2": "ずらし斬り上げLv2",
    "Offset Rising Slash Lv3": "ずらし斬り上げLv3",
    "Follow-up Cross Slash Lv1 1": "派生十字斬りLv1[1]",
    "Follow-up Cross Slash Lv1 2": "派生十字斬りLv1[2]",
    "Follow-up Cross Slash Lv2 1": "派生十字斬りLv2[1]",
    "Follow-up Cross Slash Lv2 2": "派生十字斬りLv2[2]",
    "Follow-up Cross Slash Lv3 1": "派生十字斬りLv3[1]",
    "Follow-up Cross Slash Lv3 2": "派生十字斬りLv3[2]",
    "Kick": "キック",
    "Side Blow": "側面殴り",
    "Strong Charged Slash Lv1": "強溜め斬りLv1",
    "Strong Charged Slash Lv2": "強溜め斬りLv2",
    "Strong Charged Slash Lv3": "強溜め斬りLv3",
    "Strong Wide Slash Lv1": "強薙ぎ払いLv1",
    "Strong Wide Slash Lv2": "強薙ぎ払いLv2",
    "Strong Wide Slash Lv3": "強薙ぎ払いLv3",
    "Tackle": "タックル",
    "Tackle Lv1": "タックルLv1",
    "Tackle Lv2": "タックルLv2",
    "Tackle Lv3": "タックルLv3",
    "Leaping Wide Slash": "飛び込み薙ぎ払い",
    "Leaping Wide Slash Lv1": "飛び込み薙ぎ払いLv1",
    "Leaping Wide Slash Lv2": "飛び込み薙ぎ払いLv2",
    "Leaping Wide Slash Lv3": "飛び込み薙ぎ払いLv3",
    "True Charged Slash Lv1 1": "真・溜め斬りLv1[1]",
    "True Charged Slash Lv1 2": "真・溜め斬りLv1[2]",
    "True Charged Slash Lv1 2 (Power)": "真・溜め斬りLv1[2](強撃)",
    "True Charged Slash Lv2 1": "真・溜め斬りLv2[1]",
    "True Charged Slash Lv2 2": "真・溜め斬りLv2[2]",
    "True Charged Slash Lv2 2 (Power)": "真・溜め斬りLv2[2](強撃)",
    "True Charged Slash Lv3 1": "真・溜め斬りLv3[1]",
    "True Charged Slash Lv3 2": "真・溜め斬りLv3[2]",
    "True Charged Slash Lv3 2 (Power)": "真・溜め斬りLv3[2](強撃)",
    "Focus Slash: Perforate": "集中斬り：貫通",
    "Jumping Charged Slash": "ジャンプ溜め斬り",
    "Jumping Charged Slash Lv1": "ジャンプ溜め斬りLv1",
    "Jumping Charged Slash Lv2": "ジャンプ溜め斬りLv2",
    "Jumping Charged Slash Lv3": "ジャンプ溜め斬りLv3",
    "Plunging Thrust": "突き刺し",
}

# ─── 太刀 ───
TRANSLATIONS["太刀"] = {
    "Overhead Slash I": "縦斬りI",
    "Overhead Slash II": "縦斬りII",
    "Crescent Slash": "三日月斬り",
    "Crimson Slash I 1": "緋刃斬りI[1]",
    "Crimson Slash I 2": "緋刃斬りI[2]",
    "Crimson Slash II 1": "緋刃斬りII[1]",
    "Crimson Slash II 2": "緋刃斬りII[2]",
    "Crimson Slash III 1": "緋刃斬りIII[1]",
    "Crimson Slash III 2": "緋刃斬りIII[2]",
    "Crimson Slash III 3": "緋刃斬りIII[3]",
    "Thrust": "突き",
    "Rising Slash": "斬り上げ",
    "Fade Slash": "移動斬り",
    "Spirit Blade I": "気刃斬りI",
    "Spirit Blade I (No Gauge)": "気刃斬りI(練気ゲージ無)",
    "Directional Spirit Blade I 1": "方向気刃斬りI[1]",
    "Directional Spirit Blade I 1 (No Gauge)": "方向気刃斬りI[1](練気ゲージ無)",
    "Spirit Blade II": "気刃斬りII",
    "Spirit Blade II (No Gauge)": "気刃斬りII(練気ゲージ無)",
    "Directional Spirit Blade II 1": "方向気刃斬りII[1]",
    "Directional Spirit Blade II 2": "方向気刃斬りII[2]",
    "Directional Spirit Blade II 1 (No Gauge)": "方向気刃斬りII[1](練気ゲージ無)",
    "Directional Spirit Blade II 2 (No Gauge)": "方向気刃斬りII[2](練気ゲージ無)",
    "Spirit Blade III 1": "気刃斬りIII[1]",
    "Spirit Blade III 2": "気刃斬りIII[2]",
    "Spirit Blade III 3": "気刃斬りIII[3]",
    "Spirit Blade III 1 (No Gauge)": "気刃斬りIII[1](練気ゲージ無)",
    "Spirit Blade III 2 (No Gauge)": "気刃斬りIII[2](練気ゲージ無)",
    "Spirit Blade III 3 (No Gauge)": "気刃斬りIII[3](練気ゲージ無)",
    "Spirit Roundslash": "気刃大回転斬り",
    "Spirit Roundslash (Red)": "気刃大回転斬り(赤)",
    "Spirit Roundslash (No Gauge)": "気刃大回転斬り(練気ゲージ無)",
    "Spinning Crimson Slash": "回転緋刃斬り",
    "Spirit Step Slash": "気刃踏み込み斬り",
    "Spirit Step Slash (No Gauge)": "気刃踏み込み斬り(練気ゲージ無)",
    "Jumping Slash": "ジャンプ斬り",
    "Jumping Spirit Blade I": "ジャンプ気刃斬りI",
    "Jumping Spirit Blade I (No Gauge)": "ジャンプ気刃斬りI(練気ゲージ無)",
    "Jumping Spirit Blade II 1": "ジャンプ気刃斬りII[1]",
    "Jumping Spirit Blade II 2": "ジャンプ気刃斬りII[2]",
    "Jumping Spirit Blade II 1 (No Gauge)": "ジャンプ気刃斬りII[1](練気ゲージ無)",
    "Jumping Spirit Blade II 2 (No Gauge)": "ジャンプ気刃斬りII[2](練気ゲージ無)",
    "Jumping Spirit Blade III 1": "ジャンプ気刃斬りIII[1]",
    "Jumping Spirit Blade III 2": "ジャンプ気刃斬りIII[2]",
    "Jumping Spirit Blade III 3 (Not Used?)": "ジャンプ気刃斬りIII[3](未使用?)",
    "Jumping Spirit Blade III 3 (No Gauge)": "ジャンプ気刃斬りIII[3](練気ゲージ無)",
    "Jumping Rising Slash": "ジャンプ斬り上げ",
    "Aerial Draw Spirit Blade": "空中抜刀気刃斬り",
    "Aerial Draw Spirit Blade (No Gauge)": "空中抜刀気刃斬り(練気ゲージ無)",
    "Foresight Slash": "見切り斬り",
    "Foresight Slash (No Gauge)": "見切り斬り(練気ゲージ無)",
    "Foresight Slash (Success)": "見切り斬り(成功)",
    "Foresight Whirl Slash 1": "見切り旋回斬り[1]",
    "Foresight Whirl Slash 2": "見切り旋回斬り[2]",
    "Foresight Whirl Slash 1 (Sucess)": "見切り旋回斬り[1](成功)",
    "Foresight Whirl Slash 2 (Success)": "見切り旋回斬り[2](成功)",
    "Iai Slash 1": "居合斬り[1]",
    "Iai Slash 2": "居合斬り[2]",
    "Iai Spirit Slash 1 (None)": "居合気刃斬り[1](無色)",
    "Iai Spirit Slash 1 (White)": "居合気刃斬り[1](白)",
    "Iai Spirit Slash 2 (White) (Success)": "居合気刃斬り[2](白・成功)",
    "Iai Spirit Slash 1 (Yellow)": "居合気刃斬り[1](黄)",
    "Iai Spirit Slash 2 (Yellow) (Success)": "居合気刃斬り[2](黄・成功)",
    "Iai Spirit Slash 1 (Red)": "居合気刃斬り[1](赤)",
    "Iai Spirit Slash 2 (Red) (Success)": "居合気刃斬り[2](赤・成功)",
    "Spirit Thrust": "気刃突き",
    "Spirit Helmbreaker (White)": "兜割(白)",
    "Spirit Helmbreaker (Yellow)": "兜割(黄)",
    "Spirit Helmbreaker (Red)": "兜割(赤)",
    "Spirit Release Slash 1": "気刃解放斬り[1]",
    "Spirit Release Slash 2": "気刃解放斬り[2]",
    "Spirit Release Slash 3": "気刃解放斬り[3]",
    "Spirit Release Slash 4": "気刃解放斬り[4]",
    "Spirit Release Slash 5": "気刃解放斬り[5]",
}

# ─── 片手剣 ───
TRANSLATIONS["片手剣"] = {
    "Advancing Slash": "突進斬り",
    "Rising Slash": "斬り上げ",
    "Chop": "斬り下ろし",
    "Side Slash": "横斬り",
    "Diagonal Rising Slash": "斜め斬り上げ",
    "Diagonal Chop": "斜め斬り下ろし",
    "Lateral Slash": "水平斬り",
    "Return Stroke": "返し斬り",
    "Spinning Rising Slash": "回転斬り上げ",
    "Roundslash": "回転斬り",
    "Spinning Reaper": "回転斬り(強)",
    "Shield Attack": "盾攻撃",
    "Shield Bash": "盾殴り",
    "Hard Basher": "ハードバッシュ",
    "Guard Slash": "ガード斬り",
    "Charged Slash": "溜め斬り",
    "Scaling Slash": "駆け上がり斬り",
    "Jumping Rising Slash": "ジャンプ斬り上げ",
    "Jumping Advancing Slash": "ジャンプ突進斬り",
    "Jumping Slash": "ジャンプ斬り",
    "Falling Bash 1": "フォーリングバッシュ[1]",
    "Falling Bash 2": "フォーリングバッシュ[2]",
    "Plunging Thrust": "突き刺し",
    "Sliding Sweep 1": "スライディング薙ぎ[1]",
    "Sliding Sweep 2": "スライディング薙ぎ[2]",
    "Sliding Slash 1": "スライディング斬り[1]",
    "Sliding Slash 2": "スライディング斬り[2]",
    "Leaping Slash": "飛び込み斬り",
    "Perfect Rush I 1": "ジャストラッシュI[1]",
    "Perfect Rush I 2": "ジャストラッシュI[2]",
    "Perfect Rush I 3": "ジャストラッシュI[3]",
    "Perfect Rush II": "ジャストラッシュII",
    "Perfect Rush III": "ジャストラッシュIII",
    "Perfect Rush III Hits": "ジャストラッシュIII(多段)",
    "Power Perfect Rush I 1": "強化ジャストラッシュI[1]",
    "Power Perfect Rush I 2": "強化ジャストラッシュI[2]",
    "Power Perfect Rush I 3": "強化ジャストラッシュI[3]",
    "Power Perfect Rush II": "強化ジャストラッシュII",
    "Power Perfect Rush III": "強化ジャストラッシュIII",
    "Power Perfect Rush III Hits": "強化ジャストラッシュIII(多段)",
    "Charged Chop 1": "溜め斬り下ろし[1]",
    "Charged Chop 2": "溜め斬り下ろし[2]",
    "Charged Chop 3": "溜め斬り下ろし[3]",
    "Power Charged Chop 3": "強溜め斬り下ろし[3]",
    "Counter Slash": "カウンター斬り",
    "Recovering Slash": "回復斬り",
    "Focus Strike: Vital Stab": "集中攻撃：急所突き",
    "Focus Strike: Vital Stab (Opening Wound)": "集中攻撃：急所突き(裂傷)",
    "Falling Slash": "落下斬り",
    "Falling Slash Hits": "落下斬り(多段)",
    "Upswing Bash": "振り上げ殴り",
    "Upswing Bash Hits": "振り上げ殴り(多段)",
}

# ─── 双剣 ───
TRANSLATIONS["双剣"] = {
    "Double Slash 1": "二連斬り[1]",
    "Double Slash 2": "二連斬り[2]",
    "Double Slash Return Stroke": "二連斬り返し",
    "Circle Slash 1": "車輪斬り[1]",
    "Circle Slash 2": "車輪斬り[2]",
    "Circle Slash 3": "車輪斬り[3]",
    "Demon Fangs": "鬼人牙",
    "Twofold Demon Slash 1": "二段鬼人斬り[1]",
    "Twofold Demon Slash 2": "二段鬼人斬り[2]",
    "Sixfold Demon Slash 1": "六段鬼人斬り[1]",
    "Sixfold Demon Slash 2": "六段鬼人斬り[2]",
    "Sixfold Demon Slash 3": "六段鬼人斬り[3]",
    "Fade Slash": "回避斬り",
    "Rising Slash": "斬り上げ",
    "Demon Rising Slash": "鬼人斬り上げ",
    "Lunging Strike 1-2": "突進連斬[1-2]",
    "Lunging Strike 3-4": "突進連斬[3-4]",
    "Side/Back Lunging Strike": "側面/後方突進連斬",
    "Demon Flurry Rush 1": "鬼人突進連斬[1]",
    "Demon Flurry Rush 2": "鬼人突進連斬[2]",
    "Demon Flurry Rush 3": "鬼人突進連斬[3]",
    "Left Spinning Slash 1": "左回転斬り[1]",
    "Left Spinning Slash 2": "左回転斬り[2]",
    "Left Spinning Slash 3": "左回転斬り[3]",
    "Right Spinning Slash 1": "右回転斬り[1]",
    "Right Spinning Slash 2": "右回転斬り[2]",
    "Right Spinning Slash 3": "右回転斬り[3]",
    "Left Double Roundslash 1": "左二連回転斬り[1]",
    "Left Double Roundslash 2": "左二連回転斬り[2]",
    "Left Double Roundslash 3": "左二連回転斬り[3]",
    "Right Double Roundslash 1": "右二連回転斬り[1]",
    "Right Double Roundslash 2": "右二連回転斬り[2]",
    "Right Double Roundslash 3": "右二連回転斬り[3]",
    "Blade Dance I 1": "乱舞I[1]",
    "Blade Dance I 2": "乱舞I[2]",
    "Blade Dance I 3": "乱舞I[3]",
    "Blade Dance I 4": "乱舞I[4]",
    "Blade Dance I 5": "乱舞I[5]",
    "Blade Dance I 6": "乱舞I[6]",
    "Blade Dance II 1": "乱舞II[1]",
    "Blade Dance II 2": "乱舞II[2]",
    "Blade Dance II 3": "乱舞II[3]",
    "Blade Dance III 1": "乱舞III[1]",
    "Blade Dance III 2": "乱舞III[2]",
    "Blade Dance III 3": "乱舞III[3]",
    "Blade Dance III 4": "乱舞III[4]",
    "Blade Dance III 5": "乱舞III[5]",
    "Blade Dance III 6": "乱舞III[6]",
    "Blade Dance III 7": "乱舞III[7]",
    "Blade Dance III 8": "乱舞III[8]",
    "Blade Dance III 9": "乱舞III[9]",
    "Blade Dance III 10": "乱舞III[10]",
    "Demon Flurry I": "鬼人連斬I",
    "Demon Flurry II 1": "鬼人連斬II[1]",
    "Demon Flurry II 2": "鬼人連斬II[2]",
    "Demon Flurry II 3": "鬼人連斬II[3]",
    "Jumping Doubleslash 1": "ジャンプ二連斬り[1]",
    "Jumping Doubleslash 2": "ジャンプ二連斬り[2]",
    "Midair Spinning Blade Dance 1": "空中回転乱舞[1]",
    "Midair Spinning Blade Dance 2": "空中回転乱舞[2]",
    "Midair Spinning Blade Dance 3": "空中回転乱舞[3]",
    "Midair Spinning Blade Dance 4": "空中回転乱舞[4]",
    "Midair Spinning Blade Dance Finisher 1": "空中回転乱舞フィニッシュ[1]",
    "Midair Spinning Blade Dance Finisher 2": "空中回転乱舞フィニッシュ[2]",
    "Midair Spinning Blade Dance Finisher 3": "空中回転乱舞フィニッシュ[3]",
    "Heavenly Blade Dance 1": "天舞[1]",
    "Heavenly Blade Dance 2": "天舞[2]",
    "Heavenly Blade Dance 3": "天舞[3]",
    "Heavenly Blade Dance 4": "天舞[4]",
    "Heavenly Blade Dance Finisher 1": "天舞フィニッシュ[1]",
    "Heavenly Blade Dance Finisher 2": "天舞フィニッシュ[2]",
    "Heavenly Blade Dance Finisher 3": "天舞フィニッシュ[3]",
    "Sliding Slash 1": "スライディング斬り[1]",
    "Sliding Slash 2": "スライディング斬り[2]",
    "Perfect Evade 1": "ジャスト回避[1]",
    "Perfect Evade 2": "ジャスト回避[2]",
    "Screw Slicer 1": "螺旋斬り[1]",
    "Screw Slicer 2": "螺旋斬り[2]",
    "Screw Slicer 3": "螺旋斬り[3]",
    "Screw Slicer 4": "螺旋斬り[4]",
    "Focus Strike: Turning Tide": "集中攻撃：逆転斬り",
    "Focus Strike: Turning Tide Follow-Up": "集中攻撃：逆転斬り追撃",
    "Turning Tidedrill 1": "逆転螺旋[1]",
    "Turning Tidedrill 2": "逆転螺旋[2]",
    "Turning Tidedrill 3": "逆転螺旋[3]",
    "Turning Tidedrill 4": "逆転螺旋[4]",
    "Turning Tidedrill 5": "逆転螺旋[5]",
    "Turning Tidedrill 6": "逆転螺旋[6]",
    "Turning Tidedrill 7": "逆転螺旋[7]",
    "Turning Tidedrill 8": "逆転螺旋[8]",
}

# ─── ハンマー ───
TRANSLATIONS["ハンマー"] = {
    "Swing": "振り",
    "Follow-up": "追撃",
    "Overhead Smash I": "叩きつけI",
    "Overhead Smash II": "叩きつけII",
    "Upswing": "振り上げ",
    "Side Smash": "横殴り",
    "Big Bang I": "ビッグバンI",
    "Big Bang II": "ビッグバンII",
    "Big Bang III": "ビッグバンIII",
    "Big Bang IV": "ビッグバンIV",
    "Big Bang Finisher 1": "ビッグバンフィニッシュ[1]",
    "Big Bang Finisher 2": "ビッグバンフィニッシュ[2]",
    "Charged Side Blow": "溜め横殴り",
    "Charged Follow-up": "溜め追撃",
    "Charged Upswing": "溜め振り上げ",
    "Charged Big Bang 1": "溜めビッグバン[1]",
    "Charged Big Bang 2": "溜めビッグバン[2]",
    "Spinning Bludgeon Start": "回転攻撃(開始)",
    "Spinning Bludgeon Mid": "回転攻撃(継続)",
    "Spinning Bludgeon Finish": "回転攻撃(終了)",
    "Spinning Side Smash": "回転横殴り",
    "Spinning Follow-up": "回転追撃",
    "Spinning Strong Upswing": "回転強振り上げ",
    "Mighty Charge Upswing": "力溜め振り上げ",
    "Mighty Charge Slam 1": "力溜め叩きつけ[1]",
    "Mighty Charge Slam 2": "力溜め叩きつけ[2]",
    "Mighty Charge Slam 3": "力溜め叩きつけ[3]",
    "Follow-Up Spinslam Spin": "追撃回転叩きつけ(回転)",
    "Follow-Up Spinslam 1": "追撃回転叩きつけ[1]",
    "Follow-Up Spinslam 2": "追撃回転叩きつけ[2]",
    "Focus Blow: Earthquake": "集中攻撃：震打",
    "Focus Blow: Earthquake Spin": "集中攻撃：震打(回転)",
    "Focus Blow: Earthquake Finisher": "集中攻撃：震打(フィニッシュ)",
    "Jumping Smash": "ジャンプ叩きつけ",
    "Jumping Charged Attack I": "ジャンプ溜め攻撃I",
    "Jumping Charged Attack II": "ジャンプ溜め攻撃II",
    "Jumping Charged Attack III": "ジャンプ溜め攻撃III",
}

# ─── 狩猟笛 ───
TRANSLATIONS["狩猟笛"] = {
    "Forward Smash": "前方攻撃",
    "Left Swing": "左ぶん回し",
    "Right Swing": "右ぶん回し",
    "Flourish 1": "連音攻撃[1]",
    "Flourish 2": "連音攻撃[2]",
    "Backwards Strike": "後方攻撃",
    "Overhead Smash 1": "叩きつけ[1]",
    "Overhead Smash 2": "叩きつけ[2]",
    "Overhead Smash Follow-up Attack": "叩きつけ追撃",
    "Hilt Stab": "柄突き",
    "Neutral / Forward Perform": "前方演奏攻撃",
    "Side Perform": "側方演奏攻撃",
    "Back Perform": "後方演奏攻撃",
    "Performance Beat I": "演奏I",
    "Performance Beat I (Power)": "演奏I(強化)",
    "Performance Beat II": "演奏II",
    "Performance Beat II (Power)": "演奏II(強化)",
    "Encore 1": "アンコール[1]",
    "Encore 2": "アンコール[2]",
    "Encore 2 (Power)": "アンコール[2](強化)",
    "Offset Melody": "ずらし旋律",
    "Resounding Melody 1": "響旋律[1]",
    "Resounding Melody 2": "響旋律[2]",
    "Resounding Melody 3": "響旋律[3]",
    "Resounding Melody Soundwaves": "響旋律(衝撃波)",
    "Perform Soundwave": "演奏衝撃波",
    "Song Soundwave": "旋律衝撃波",
    "Echo Bubble": "響泡",
    "Echo Bubble (Note)": "響泡(音符)",
    "Echo Bubble (Song)": "響泡(旋律)",
    "Echo Wave (Blunt)": "震打波(打撃)",
    "Echo Wave (Blunt) II": "震打波(打撃)II",
    "Echo Wave (Blunt) III": "震打波(打撃)III",
    "Echo Wave (Slash)": "震打波(斬撃)",
    "Echo Wave (Slash) II": "震打波(斬撃)II",
    "Echo Wave (Slash) III": "震打波(斬撃)III",
    "Echo Wave (Fire)": "震打波(火)",
    "Echo Wave (Fire) II": "震打波(火)II",
    "Echo Wave (Fire) III": "震打波(火)III",
    "Echo Wave (Water)": "震打波(水)",
    "Echo Wave (Water) II": "震打波(水)II",
    "Echo Wave (Water) III": "震打波(水)III",
    "Echo Wave (Thunder)": "震打波(雷)",
    "Echo Wave (Thunder) II": "震打波(雷)II",
    "Echo Wave (Thunder) III": "震打波(雷)III",
    "Echo Wave (Ice)": "震打波(氷)",
    "Echo Wave (Ice) II": "震打波(氷)II",
    "Echo Wave (Ice) III": "震打波(氷)III",
    "Echo Wave (Dragon)": "震打波(龍)",
    "Echo Wave (Dragon) II": "震打波(龍)II",
    "Echo Wave (Dragon) III": "震打波(龍)III",
    "Echo Wave (Blast)": "震打波(爆破)",
    "Echo Wave (Blast) II": "震打波(爆破)II",
    "Echo Wave (Blast) III": "震打波(爆破)III",
    "Echo Wave (Paralysis)": "震打波(麻痺)",
    "Echo Wave (Paralysis) II": "震打波(麻痺)II",
    "Echo Wave (Paralysis) III": "震打波(麻痺)III",
    "Echo Wave (Poison)": "震打波(毒)",
    "Echo Wave (Poison) II": "震打波(毒)II",
    "Echo Wave (Poison) III": "震打波(毒)III",
    "Echo Wave (Sleep)": "震打波(睡眠)",
    "Echo Wave (Sleep) II": "震打波(睡眠)II",
    "Echo Wave (Sleep) III": "震打波(睡眠)III",
}

# ─── ランス ───
TRANSLATIONS["ランス"] = {
    "Mid Thrust I / II": "中段突きI/II",
    "Mid Thrust III": "中段突きIII",
    "High Thrust I / II": "上段突きI/II",
    "High Thrust III": "上段突きIII",
    "Triple Thrust 1 / 2": "三連突き[1/2]",
    "Triple Thrust 3": "三連突き[3]",
    "Charge Counter": "突進カウンター",
    "Charge Counter Lv1": "突進カウンターLv1",
    "Charge Counter Lv2": "突進カウンターLv2",
    "Charge Counter Lv3": "突進カウンターLv3",
    "Double Counter-thrust 1": "二連カウンター突き[1]",
    "Double Counter-thrust 2": "二連カウンター突き[2]",
    "Double Counter-thrust Lv1 1": "二連カウンター突きLv1[1]",
    "Double Counter-thrust Lv1 2": "二連カウンター突きLv1[2]",
    "Double Counter-thrust Lv2 1": "二連カウンター突きLv2[1]",
    "Double Counter-thrust Lv2 2": "二連カウンター突きLv2[2]",
    "Double Counter-thrust Lv3 1": "二連カウンター突きLv3[1]",
    "Double Counter-thrust Lv3 2": "二連カウンター突きLv3[2]",
    "Leaping Thrust": "飛び込み突き",
    "Wide Sweep": "薙ぎ払い",
    "Shield Attack": "盾攻撃",
    "Guard Thrust": "ガード突き",
    "Dash Attack": "突進突き",
    "Finishing Thrust": "フィニッシュ突き",
    "Finishing Twin Thrust 1": "フィニッシュ二連突き[1]",
    "Finishing Twin Thrust 2": "フィニッシュ二連突き[2]",
    "Reverse Attack": "反転攻撃",
    "Advancing Jump": "突進ジャンプ",
    "Reverse Attack (High Speed)": "反転攻撃(高速)",
    "Advancing Jump Thrust": "突進ジャンプ突き",
    "Advancing Jump Thrust (High Speed)": "突進ジャンプ突き(高速)",
    "Jumping Thrust": "ジャンプ突き",
    "Guard Counter": "ガードカウンター",
    "Perfect Guard Counter": "ジャストガードカウンター",
    "Return Thrust": "返し突き",
    "Return Thrust (Power)": "返し突き(強化)",
    "Payback Thrust 1": "報復突き[1]",
    "Payback Thrust 1 (Power)": "報復突き[1](強化)",
    "Payback Thrust 2": "報復突き[2]",
    "Retribution Thrust 1": "応報突き[1]",
    "Retribution Thrust 1 (Power)": "応報突き[1](強化)",
    "Retribution Thrust 2": "応報突き[2]",
    "Grand Retribution Thrust 1": "大応報突き[1]",
    "Grand Retribution Thrust 2": "大応報突き[2]",
    "Grand Retribution Thrust 3": "大応報突き[3]",
    "Follow-up Dash Attack": "追撃突進突き",
    "Focus Strike: Victory Thrust 1": "集中攻撃：勝利の突き[1]",
    "Focus Strike: Victory Thrust 2": "集中攻撃：勝利の突き[2]",
    "Focus Strike: Victory Thrust 3": "集中攻撃：勝利の突き[3]",
    "Power Clash Finisher 1": "パワークラッシュ[1]",
    "Power Clash Finisher 2": "パワークラッシュ[2]",
}

# ─── ガンランス ───
TRANSLATIONS["ガンランス"] = {
    "Lateral Thrust I / II": "水平突きI/II",
    "Lunging Upthrust": "踏み込み突き上げ",
    "Rising Slash": "斬り上げ",
    "Guard Thrust": "ガード突き",
    "Overhead Smash": "叩きつけ",
    "Wide Sweep / Moving Wide Sweep / Aerial Burst": "薙ぎ払い",
    "(Multi) Wyrmstake Full Blast Sweep": "竜杭フルバースト薙ぎ払い",
    "Wyrmstake Thrust": "竜杭突き",
    "Wyrmstake Full Blast Thrust": "竜杭フルバースト突き",
    "Wyrmstake Attach": "竜杭装着",
    "Jumping Thrust": "ジャンプ突き",
    "Jumping Smash": "ジャンプ叩きつけ",
    "Jumping Rising Slash": "ジャンプ斬り上げ",
    "Focus Strike: Drake Auger": "集中攻撃：竜穿",
}

# ─── スラッシュアックス ───
TRANSLATIONS["スラッシュアックス"] = {
    "Axe: Overhead Slash": "斧：縦斬り",
    "Axe: Side Slash": "斧：横斬り",
    "Axe: Spiral Burst Slash 1": "斧：螺旋斬り[1]",
    "Axe: Spiral Burst Slash 2": "斧：螺旋斬り[2]",
    "Axe: Forward Slash": "斧：前方斬り",
    "Axe: Forward Overhead Slash": "斧：前方縦斬り",
    "Axe: Fade Slash": "斧：回避斬り",
    "Axe: Offset Rising Slash": "斧：ずらし斬り上げ",
    "Axe: Follow-up Heavy Slam 1": "斧：追撃叩きつけ[1]",
    "Axe: Follow-up Heavy Slam 2": "斧：追撃叩きつけ[2]",
    "Axe: Follow-up Morph Slash": "斧：追撃変形斬り",
    "Axe: Follow-up Morph Slash Explosion (Power Phial)": "斧：追撃変形斬り爆発(強撃ビン)",
    "Axe: Follow-up Morph Slash Explosion (Element Phial)": "斧：追撃変形斬り爆発(属性ビン)",
    "Axe: Wild Slash Left": "斧：振り回し(左)",
    "Axe: Wild Slash Right": "斧：振り回し(右)",
    "Axe: Heavy Slam 1": "斧：叩きつけ[1]",
    "Axe: Heavy Slam 2": "斧：叩きつけ[2]",
    "Axe: Morph Sweep 1": "斧：変形薙ぎ払い[1]",
    "Axe: Morph Sweep 2": "斧：変形薙ぎ払い[2]",
    "Axe: Morph Sweep 3": "斧：変形薙ぎ払い[3]",
    "Axe: Morph Slash": "斧：変形斬り",
    "Axe: Morph Rising Double Slash 1": "斧：変形斬り上げ二連[1]",
    "Axe: Morph Rising Double Slash 2": "斧：変形斬り上げ二連[2]",
    "Sword: Overhead Slash": "剣：縦斬り",
    "Sword: Left Rising Slash": "剣：左斬り上げ",
    "Sword: Right Rising Slash": "剣：右斬り上げ",
    "Sword: Triple Slash 1": "剣：三連斬り[1]",
    "Sword: Double Slash 1 / Triple Slash 2": "剣：二連斬り/三連斬り[2]",
    "Sword: Double Slash 2 / Triple Slash 3": "剣：二連斬り/三連斬り[3]",
    "Sword: Heavenward Flurry 1": "剣：天連斬り[1]",
    "Sword: Heavenward Flurry 2": "剣：天連斬り[2]",
    "Sword: Morph Slash": "剣：変形斬り",
    "Sword: Morph Double Slash 1": "剣：変形二連斬り[1]",
    "Sword: Morph Double Slash 2": "剣：変形二連斬り[2]",
    "Sword: Amped State Phial (Power Phial)": "剣：高出力ビン(強撃ビン)",
    "Sword: Amped State Phial (Element Phial)": "剣：高出力ビン(属性ビン)",
    "Unbridled Slash": "解放斬り",
    "Unbridled Slash Explosion (Power Phial)": "解放斬り爆発(強撃ビン)",
    "Unbridled Slash Explosion (Element Phial)": "解放斬り爆発(属性ビン)",
    "Full Release Slash 1": "全解放斬り[1]",
    "Full Release Slash 2": "全解放斬り[2]",
    "Full Release Slash Explosion 1 (Power Phial)": "全解放斬り爆発[1](強撃ビン)",
    "Full Release Slash Explosion 1 (Element Phial)": "全解放斬り爆発[1](属性ビン)",
    "Full Release Slash Explosion 2 (Power Phial)": "全解放斬り爆発[2](強撃ビン)",
    "Full Release Slash Explosion 2 (Element Phial)": "全解放斬り爆発[2](属性ビン)",
    "Elemental Discharge": "属性解放突き",
    "Elemental Discharge Tick": "属性解放突き(多段)",
    "Elemental Discharge Finisher": "属性解放突きフィニッシュ",
    "Finishing Discharge": "零距離属性解放突き",
    "Zero Sum Discharge Finisher": "零距離属性解放突きフィニッシュ",
    "Zero Sum Finishing Discharge": "零距離解放フィニッシュ",
}

# ─── チャージアックス ───
TRANSLATIONS["チャージアックス"] = {
    "Sword: Forward Slash": "剣：前方斬り",
    "Sword: Weak Slash": "剣：弱斬り",
    "Sword: Return Stroke": "剣：返し斬り",
    "Sword: Roundslash": "剣：回転斬り",
    "Sword: Fade Slash": "剣：回避斬り",
    "Sword: Charged Rising Slash": "剣：溜め斬り上げ",
    "Sword: Charged Double Slash 1": "剣：溜め二連斬り[1]",
    "Sword: Charged Double Slash 2": "剣：溜め二連斬り[2]",
    "Sword: Shield Thrust 1": "剣：盾突き[1]",
    "Sword: Shield Thrust 2": "剣：盾突き[2]",
    "Sword: Condensed Elemental Slash": "剣：属性強化斬り",
    "Sword: Condensed Elemental Slash Impact Phial": "剣：属性強化斬り(榴弾ビン)",
    "Sword: Condensed Elemental Slash Element Phial": "剣：属性強化斬り(強属性ビン)",
    "Sword: Morph Slash": "剣：変形斬り",
    "Axe: Rising Slash": "斧：斬り上げ",
    "Axe: Overhead Slash": "斧：縦斬り",
    "Axe: Dash Slam": "斧：突進叩きつけ",
    "Axe: Lateral Fade Slash / Backstep Slash": "斧：横回避斬り/バックステップ斬り",
    "Axe: Morph Slash / Elemental Roundslash": "斧：変形斬り/属性回転斬り",
    "Axe: Elemental Discharge I": "斧：属性解放斬りI",
    "Axe: Elemental Discharge II 1": "斧：属性解放斬りII[1]",
    "Axe: Elemental Discharge II 2": "斧：属性解放斬りII[2]",
    "Axe: Amped Elemental Discharge": "斧：高出力属性解放斬り",
    "Axe: Amped Elemental Discharge Follow-up": "斧：高出力属性解放斬り追撃",
    "Axe: Super Amped Elemental Discharge 1": "斧：超高出力属性解放斬り[1]",
    "Axe: Super Amped Elemental Discharge 2": "斧：超高出力属性解放斬り[2]",
    "Axe: Super Amped Elemental Discharge 3": "斧：超高出力属性解放斬り[3]",
    "Savage Axe Slash": "斧強化斬り",
    "Power Axe Tick": "斧強化(多段)",
    "Impact Phial (Sword)": "榴弾ビン(剣)",
    "Impact Phial (ED)": "榴弾ビン(解放斬り)",
    "Overcharged Impact Phial (ED)": "過充填榴弾ビン(解放斬り)",
    "Impact Phial (AED)": "榴弾ビン(高出力)",
    "Overcharged Impact Phial (AED)": "過充填榴弾ビン(高出力)",
    "Impact Phial (SAED)": "榴弾ビン(超高出力)",
    "Overcharged Impact Phial (SAED)": "過充填榴弾ビン(超高出力)",
    "Element Phial (Sword)": "強属性ビン(剣)",
    "Element Phial (ED)": "強属性ビン(解放斬り)",
    "Overcharged Element Phial (ED)": "過充填強属性ビン(解放斬り)",
    "Element Phial (AED)": "強属性ビン(高出力)",
    "Overcharged Element Phial (AED)": "過充填強属性ビン(高出力)",
    "Element Phial (SAED)": "強属性ビン(超高出力)",
    "Overcharged Element Phial (SAED)": "過充填強属性ビン(超高出力)",
    "Focus Slash: Double Rend": "集中斬り：二連裂き",
    "Focus Strike Savage Axe": "集中攻撃：斧強化",
    "Focus Strike Savage Axe Ticks": "集中攻撃：斧強化(多段)",
    "Sword Jumping Slash / Axe Jumping Morph Slash": "剣ジャンプ斬り/斧ジャンプ変形斬り",
    "Axe Jumping Slash / Sword Jumping Morph Slash": "斧ジャンプ斬り/剣ジャンプ変形斬り",
}

# ─── 操虫棍 ───
TRANSLATIONS["操虫棍"] = {
    "Rising Slash Combo 1": "斬り上げ連携[1]",
    "Rising Slash Combo 2": "斬り上げ連携[2]",
    "Reaping Slash": "薙ぎ払い",
    "Double Slash 1": "二連斬り[1]",
    "Double Slash 2": "二連斬り[2]",
    "Sidestep Slash": "回避斬り",
    "Sidestep Slash Combo 1": "回避斬り連携[1]",
    "Sidestep Slash Combo 2": "回避斬り連携[2]",
    "Sidestep Slash Combo 1 (Forward)": "回避斬り連携[1](前方)",
    "Sidestep Slash Combo 2 (Forward)": "回避斬り連携[2](前方)",
    "Wide Sweep": "広域薙ぎ払い",
    "Leaping Slash": "飛び込み斬り",
    "Overhead Smash": "叩きつけ",
    "Dodge Slash": "回避斬り",
    "Strong Rising Slash Combo 1": "強斬り上げ連携[1]",
    "Strong Rising Slash Combo 2": "強斬り上げ連携[2]",
    "Strong Rising Slash Combo 3": "強斬り上げ連携[3]",
    "Strong Reaping Slash 1": "強薙ぎ払い[1]",
    "Strong Reaping Slash 2": "強薙ぎ払い[2]",
    "Strong Double Slash 1": "強二連斬り[1]",
    "Strong Double Slash 2": "強二連斬り[2]",
    "Strong Double Slash 3": "強二連斬り[3]",
    "Strong Wide Sweep 1": "強広域薙ぎ払い[1]",
    "Strong Wide Sweep 2": "強広域薙ぎ払い[2]",
    "Tornado Slash 1": "竜巻斬り[1]",
    "Tornado Slash 2": "竜巻斬り[2]",
    "Jumping Slash": "ジャンプ斬り",
    "Jumping Advancing Slash": "ジャンプ突進斬り",
    "Strong Jumping Slash": "強ジャンプ斬り",
    "Strong Jumping Advancing Slash 1": "強ジャンプ突進斬り[1]",
    "Strong Jumping Advancing Slash 2": "強ジャンプ突進斬り[2]",
    "Strong Jumping Advancing Slash II 1": "強ジャンプ突進斬りII[1]",
    "Strong Jumping Advancing Slash II 2": "強ジャンプ突進斬りII[2]",
    "Strong Jumping Advancing Slash III 1": "強ジャンプ突進斬りIII[1]",
    "Strong Jumping Advancing Slash III 2": "強ジャンプ突進斬りIII[2]",
    "Scaling Double Slash 1": "駆け上がり二連斬り[1]",
    "Scaling Double Slash 2": "駆け上がり二連斬り[2]",
    "Descending Slash Lv1 1": "降下斬りLv1[1]",
    "Descending Slash Lv1 2": "降下斬りLv1[2]",
    "Descending Slash Lv1 3": "降下斬りLv1[3]",
    "Descending Slash Lv1 4": "降下斬りLv1[4]",
    "Descending Slash Lv2 1": "降下斬りLv2[1]",
    "Descending Slash Lv2 2": "降下斬りLv2[2]",
    "Descending Slash Lv2 3": "降下斬りLv2[3]",
    "Descending Slash Lv2 4": "降下斬りLv2[4]",
    "Strong Descending Slash Lv1 1": "強降下斬りLv1[1]",
    "Strong Descending Slash Lv1 2": "強降下斬りLv1[2]",
    "Strong Descending Slash Lv1 3-5": "強降下斬りLv1[3-5]",
    "Strong Descending Slash Lv1 6": "強降下斬りLv1[6]",
    "Strong Descending Slash Lv2 1": "強降下斬りLv2[1]",
    "Strong Descending Slash Lv2 2": "強降下斬りLv2[2]",
    "Strong Descending Slash Lv2 3-5": "強降下斬りLv2[3-5]",
    "Strong Descending Slash Lv2 6": "強降下斬りLv2[6]",
    "Descending Thrust Lv1 1": "降下突きLv1[1]",
    "Descending Thrust Lv1 2": "降下突きLv1[2]",
    "Descending Thrust Lv1 3": "降下突きLv1[3]",
    "Descending Thrust Lv2 1": "降下突きLv2[1]",
    "Descending Thrust Lv2 2": "降下突きLv2[2]",
    "Descending Thrust Lv2 3": "降下突きLv2[3]",
    "Strong Descending Thrust Lv1 1": "強降下突きLv1[1]",
    "Strong Descending Thrust Lv1 2": "強降下突きLv1[2]",
    "Strong Descending Thrust Lv1 3": "強降下突きLv1[3]",
    "Strong Descending Thrust Lv1 4-5": "強降下突きLv1[4-5]",
    "Strong Descending Thrust Lv1 6": "強降下突きLv1[6]",
    "Strong Descending Thrust Lv2 1": "強降下突きLv2[1]",
    "Strong Descending Thrust Lv2 2": "強降下突きLv2[2]",
    "Strong Descending Thrust Lv2 3": "強降下突きLv2[3]",
    "Strong Descending Thrust Lv2 4-5": "強降下突きLv2[4-5]",
    "Strong Descending Thrust Lv2 6": "強降下突きLv2[6]",
    "Rising Spiral Slash Lv1": "上昇螺旋斬りLv1",
    "Rising Spiral Slash Lv2": "上昇螺旋斬りLv2",
    "Kinsect Mark (Melee)": "猟虫マーキング(近接)",
    "Focus Thrust: Leaping Strike 1": "集中攻撃：跳躍突き[1]",
    "Focus Thrust: Leaping Strike 2": "集中攻撃：跳躍突き[2]",
    "Focus Thrust: Leaping Strike 3": "集中攻撃：跳躍突き[3]",
}

# ─── 弓 ───
TRANSLATIONS["弓"] = {
    "Charged Shot Lv1": "溜め射ちLv1",
    "Charged Shot Lv2": "溜め射ちLv2",
    "Charged Shot Lv3": "溜め射ちLv3",
    "Quick Shot": "クイックショット",
    "Power Shot Lv 1": "剛射Lv1",
    "Power Shot Lv2": "剛射Lv2",
    "Power Shot Lv3": "剛射Lv3",
    "Flying Swallow Shot Lv1": "飛燕射ちLv1",
    "Flying Swallow Shot Lv2": "飛燕射ちLv2",
    "Flying Swallow Shot Lv3": "飛燕射ちLv3",
    "Power Volley Lv1": "剛連射Lv1",
    "Power Volley Lv2": "剛連射Lv2",
    "Power Volley Lv3": "剛連射Lv3",
    "Arc Shot Lv1": "曲射Lv1",
    "Arc Shot Lv2": "曲射Lv2",
    "Arc Shot Lv3": "曲射Lv3",
    "Arc Shot Explosion": "曲射(爆発)",
    "Dragon Piercer": "竜の一矢",
    "Dragon Piercer (Fast)": "竜の一矢(短縮)",
    "Thousand Dragons": "竜の千矢",
    "Pierce Charge Shot Lv1": "貫通溜め射ちLv1",
    "Pierce Charge Shot Lv2": "貫通溜め射ちLv2",
    "Pierce Charge Shot Lv3": "貫通溜め射ちLv3",
    "Pierce Quick Shot": "貫通クイックショット",
    "Pierce Power Shot Lv1": "貫通剛射Lv1",
    "Pierce Power Shot Lv2": "貫通剛射Lv2",
    "Pierce Power Shot Lv3": "貫通剛射Lv3",
    "Pierce Flying Swallow Shot Lv1": "貫通飛燕射ちLv1",
    "Pierce Flying Swallow Shot Lv2": "貫通飛燕射ちLv2",
    "Pierce Flying Swallow Shot Lv3": "貫通飛燕射ちLv3",
    "Pierce Power Volley Lv1": "貫通剛連射Lv1",
    "Pierce Power Volley Lv2": "貫通剛連射Lv2",
    "Pierce Power Volley Lv3": "貫通剛連射Lv3",
    "Pierce Thousand Dragons": "貫通竜の千矢",
    "Tracer Arrow": "追跡矢",
    "Tracer Charged Shot": "追跡溜め射ち",
    "Tracer Charged Shot (Miss)": "追跡溜め射ち(ミス)",
    "Tracer Quick Shot": "追跡クイックショット",
    "Tracer Power Shot": "追跡剛射",
    "Tracer Power Volley": "追跡剛連射",
    "Tracer Dragon Piercer": "追跡竜の一矢",
    "Tracer Dragon Piercer (Fast)": "追跡竜の一矢(短縮)",
    "Tracer Thousand Dragons": "追跡竜の千矢",
    "Tracer Pierce Thousand Dragons": "追跡貫通竜の千矢",
    "Focus Fire: Hailstorm": "集中射撃：矢嵐",
    "Focus Fire: Hailstorm Dragon Piercer": "集中射撃：矢嵐竜の一矢",
}

# ─── ライトボウガン ───
TRANSLATIONS["ライトボウガン"] = {
    "Normal Lv1": "通常弾Lv1",
    "Normal Lv2": "通常弾Lv2",
    "Normal Lv3": "通常弾Lv3",
    "Pierce Lv1 (per hit)": "貫通弾Lv1(1HIT)",
    "Pierce Lv2 (per hit)": "貫通弾Lv2(1HIT)",
    "Pierce Lv3 (per hit)": "貫通弾Lv3(1HIT)",
    "Spread Lv1 (per pellet)": "散弾Lv1(1粒)",
    "Spread Lv2 (per pellet)": "散弾Lv2(1粒)",
    "Spread Lv3 (per pellet)": "散弾Lv3(1粒)",
    "Slicing": "斬裂弾",
    "Sticky Lv1": "徹甲榴弾Lv1",
    "Sticky Lv2": "徹甲榴弾Lv2",
    "Sticky Lv3": "徹甲榴弾Lv3",
}

# ─── ヘビィボウガン ───
TRANSLATIONS["ヘビィボウガン"] = {
    "Wyvernheart Lv1 1": "機関竜弾Lv1[1]",
    "Wyvernheart Lv1 2": "機関竜弾Lv1[2]",
    "Wyvernheart Lv1 3": "機関竜弾Lv1[3]",
    "Wyvernheart Lv1 Max": "機関竜弾Lv1[Max]",
    "Wyvernheart Lv2 1": "機関竜弾Lv2[1]",
    "Wyvernheart Lv2 2": "機関竜弾Lv2[2]",
    "Wyvernheart Lv2 3": "機関竜弾Lv2[3]",
    "Wyvernheart Lv2 Max": "機関竜弾Lv2[Max]",
}


def main() -> None:
    with open(DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)

    total = 0
    translated = 0
    missing: list[str] = []

    for weapon_type, info in data.items():
        table = TRANSLATIONS.get(weapon_type, {})
        for attack in info["attacks"]:
            total += 1
            en_name = attack["name"]
            if en_name in table:
                attack["name"] = table[en_name]
                translated += 1
            else:
                missing.append(f"  {weapon_type}: {en_name}")

    with open(DATA_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"=== モーション値日本語化完了 ===")
    print(f"  合計: {total}件  翻訳: {translated}件  未翻訳: {len(missing)}件")
    if missing:
        print(f"\n未翻訳の攻撃名:")
        for m in missing:
            print(m)


if __name__ == "__main__":
    main()
